[package]
name = "mrsc"
version = "0.3.1"
description = "mpsc with requests"
authors = ["kpcyrd <git@rxv.cc>"]
license = "MIT"
repository = "https://github.com/kpcyrd/mrsc"
readme = "README.md"

[badges]
travis-ci = { repository = "kpcyrd/mrsc" }

[dependencies]
